name: Infrastructure Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        
      - name: Setup Terraform
        run: 'hashicorp/setup-terraform@v1'
    
      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: '${{ secrets.GCP_SA_KEY }}'

      - name: Validate Terraform Configuration
        run: |
          terraform validate

      - name: Terraform Plan
        run: |
          terraform plan
        env:
          GOOGLE_CREDENTIALS: '${{ secrets.GCP_SA_KEY }}'

      - name: Terraform Apply
        run: |
          terraform apply
        env:
          GOOGLE_CREDENTIALS: '${{ secrets.GCP_SA_KEY }}'
